<?php

namespace Database\Seeders;

use App\Models\SiswaLengkap;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SiswaLengkapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $siswaData = [
            [
                'nomor_induk' => '2223.10.002',
                'nisn' => '0064018351',
                'nama_lengkap' => 'AKMAL MAULANA SIDIQ',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2006-04-12',
                'agama' => 'ISLAM',
                'anak_ke' => 1,
                'status_dalam_keluarga' => 'ANAK KANDUNG',
                'alamat' => 'Jl. Inhoftenk Gg. Perikanan II RT/RW. 07/05',
                'kelas' => 'X IPS-1',
                'tanggal_diterima' => '2022-07-18',
                'semester_diterima' => 1,
                'asal_sekolah' => null,
                'alamat_asal_sekolah' => null,
                'tahun_ijazah' => null,
                'nomor_ijazah' => null,
                'tahun_sttb' => null,
                'nomor_sttb' => null,
                'nama_ayah' => 'Heri Gandani',
                'nama_ibu' => 'Sri Nurhayati',
                'alamat_orang_tua' => 'Jl. Inhoftenk Gg. Perikanan II RT/RW. 07/05 RT RW DesaPelindung Hewan Kec. Astanaanyar',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'IRT',
                'nama_wali' => null,
                'alamat_wali' => null,
                'pekerjaan_wali' => null,
                'nomor_telepon_ayah' => null,
                'nomor_telepon_ibu' => null,
                'nomor_telepon_wali' => null,
                'is_alumni' => false,
                'is_aktif' => true,
            ],
            [
                'nomor_induk' => '2223.10.004',
                'nisn' => '0061430179',
                'nama_lengkap' => 'ALDIBA FAUZAQI FIRDAUS',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2006-08-24',
                'agama' => 'ISLAM',
                'anak_ke' => 1,
                'status_dalam_keluarga' => 'ANAK KANDUNG',
                'alamat' => 'Kp. Coblong',
                'kelas' => 'X IPS-1',
                'tanggal_diterima' => '2022-07-18',
                'semester_diterima' => 1,
                'asal_sekolah' => 'SMP MATHLAUL ANWAR MARGAHAYU',
                'alamat_asal_sekolah' => null,
                'tahun_ijazah' => null,
                'nomor_ijazah' => null,
                'tahun_sttb' => null,
                'nomor_sttb' => null,
                'nama_ayah' => 'Widodo Hadi Pranoto',
                'nama_ibu' => 'Rohanah Saidah',
                'alamat_orang_tua' => 'Kp. Coblong RT3 RW14 DesaSukamenak Kec. Margahayu',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'IRT',
                'nama_wali' => null,
                'alamat_wali' => null,
                'pekerjaan_wali' => null,
                'nomor_telepon_ayah' => '089519813320',
                'nomor_telepon_ibu' => null,
                'nomor_telepon_wali' => null,
                'is_alumni' => false,
                'is_aktif' => true,
            ],
            [
                'nomor_induk' => '2223.10.006',
                'nisn' => '0072220750',
                'nama_lengkap' => 'ANISA FITRIA',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2007-06-27',
                'agama' => 'ISLAM',
                'anak_ke' => 1,
                'status_dalam_keluarga' => 'ANAK KANDUNG',
                'alamat' => 'Kp Bojong Buah',
                'kelas' => 'X IPS-1',
                'tanggal_diterima' => '2022-07-18',
                'semester_diterima' => 1,
                'asal_sekolah' => 'SMPN 1 KATAPANG',
                'alamat_asal_sekolah' => null,
                'tahun_ijazah' => null,
                'nomor_ijazah' => null,
                'tahun_sttb' => null,
                'nomor_sttb' => null,
                'nama_ayah' => 'Rosid',
                'nama_ibu' => 'Nurwendah',
                'alamat_orang_tua' => 'Kp Bojong Buah RT5 RW3 DesaPangauban Kec. Katapang',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'IRT',
                'nama_wali' => null,
                'alamat_wali' => null,
                'pekerjaan_wali' => null,
                'nomor_telepon_ayah' => '089518084033',
                'nomor_telepon_ibu' => null,
                'nomor_telepon_wali' => null,
                'is_alumni' => false,
                'is_aktif' => true,
            ],
            [
                'nomor_induk' => '2223.10.009',
                'nisn' => '0072067664',
                'nama_lengkap' => 'BUNGA SEPTY AHMAD SYAH',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2007-09-08',
                'agama' => 'ISLAM',
                'anak_ke' => 1,
                'status_dalam_keluarga' => 'ANAK KANDUNG',
                'alamat' => 'Jl. Sadang',
                'kelas' => 'X IPS-1',
                'tanggal_diterima' => '2022-07-18',
                'semester_diterima' => 1,
                'asal_sekolah' => 'SMPN 3 MARGAHAYU',
                'alamat_asal_sekolah' => null,
                'tahun_ijazah' => null,
                'nomor_ijazah' => null,
                'tahun_sttb' => null,
                'nomor_sttb' => null,
                'nama_ayah' => 'Dadang Ahmad',
                'nama_ibu' => 'Rina Agustina',
                'alamat_orang_tua' => 'Jl. Sadang RT5 RW9 DesaMargahayu Tengah Kec. Margahayu',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'IRT',
                'nama_wali' => null,
                'alamat_wali' => null,
                'pekerjaan_wali' => null,
                'nomor_telepon_ayah' => '08992888400',
                'nomor_telepon_ibu' => null,
                'nomor_telepon_wali' => null,
                'is_alumni' => false,
                'is_aktif' => true,
            ],
            [
                'nomor_induk' => '2223.10.018',
                'nisn' => '0063684325',
                'nama_lengkap' => 'EKA RAMADHANI ADYSTIA',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2006-10-21',
                'agama' => 'ISLAM',
                'anak_ke' => 1,
                'status_dalam_keluarga' => 'ANAK KANDUNG',
                'alamat' => 'coblong',
                'kelas' => 'X IPS-1',
                'tanggal_diterima' => '2022-07-18',
                'semester_diterima' => 1,
                'asal_sekolah' => 'SMPN 2 MARGAHAYU',
                'alamat_asal_sekolah' => null,
                'tahun_ijazah' => null,
                'nomor_ijazah' => null,
                'tahun_sttb' => null,
                'nomor_sttb' => null,
                'nama_ayah' => 'A Dedy Setiawan',
                'nama_ibu' => 'Eni Kasnaenih',
                'alamat_orang_tua' => 'coblong RT3 RW14 Desasukamenak Kec. Margahayu',
                'pekerjaan_ayah' => 'Buruh',
                'pekerjaan_ibu' => 'IRT',
                'nama_wali' => null,
                'alamat_wali' => null,
                'pekerjaan_wali' => null,
                'nomor_telepon_ayah' => '0895610245060',
                'nomor_telepon_ibu' => null,
                'nomor_telepon_wali' => null,
                'is_alumni' => false,
                'is_aktif' => true,
            ],
        ];

        foreach ($siswaData as $data) {
            SiswaLengkap::create($data);
        }
    }
}
